import type { Metadata } from "next";
import { Geist, Geist_Mono, Play } from "next/font/google";
import "./globals.css";
import { MainNav } from "@/components/layout/main-nav";
import AppWalletProvider from "@/components/AppWalletProvider";
import { ReactQueryProvider } from "@/providers/provider";
import "@solana/wallet-adapter-react-ui/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const play = Play({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-play",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${play.variable} antialiased`}
      >
        <ReactQueryProvider>
          <AppWalletProvider>
            <MainNav />
            {children}
          </AppWalletProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
